package com.example.utp.Wave4.resources;

import java.util.ListResourceBundle;

public class Countries_pl_PL extends ListResourceBundle {
    private final Object[][] contents = {
            {"Aruba", "Aruba"},
            {"Afghanistan", "Afganistan"},
            {"Angola", "Angola"},
            {"Albania", "Albania"},
            {"Andorra", "Andora"},
            {"United Arab Emirates", "Zjednoczone Emiraty Arabskie"},
            {"Argentina", "Argentyna"},
            {"Armenia", "Armenia"},
            {"American Samoa", "Samoa Amerykańskie"},
            {"Antarctica", "Antarktyka"},
            {"French Southern Territories", "Francuskie Terytoria Południowe"},
            {"Antigua and Barbuda", "Antigua i Barbuda"},
            {"Australia", "Australia"},
            {"Austria", "Austria"},
            {"Azerbaijan", "Azerbejdżan"},
            {"Burundi", "Burundi"},
            {"Belgium", "Belgia"},
            {"Benin", "Benin"},
            {"Burkina Faso", "Burkina Faso"},
            {"Bangladesh", "Bangladesz"},
            {"Bulgaria", "Bułgaria"},
            {"Bahrain", "Bahrajn"},
            {"Bahamas", "Bahamy"},
            {"Bosnia and Herzegovina", "Bośnia i Hercegowina"},
            {"Belarus", "Białoruś"},
            {"Bolivia", "Boliwia"},
            {"Brazil", "Brazylia"},
            {"Canada", "Kanada"},
            {"Ivory Coast", "Wybrzeże Kości Słoniowej"},
            {"Congo", "Kongo"},
            {"Colombia", "Kolumbia"},
            {"Croatia", "Chorwacja"},
            {"Cuba", "Kuba"},
            {"Cyprus", "Cypr"},
            {"Czechia", "Czechy"},
            {"Czech Republic", "Republika Czeska"},
            {"Switzerland", "Szwajcaria"},
            {"Chie", "Chile"},
            {"China", "Chiny"},
            {"Dominica", "Dominika"},
            {"Denmark", "Dania"},
            {"Egypt", "Egipt"},
            {"Eritrea", "Erytrea"},
            {"Ethiopia", "Etiopia"},
            {"Finland", "Finlandia"},
            {"France", "Francja"},
            {"Germany", "Niemcy"},
            {"Georgia", "Gruzja"},
            {"Ghana", "Ghana"},
            {"Greece", "Grecja"},
            {"Greenland", "Grenlandia"},
            {"French Guiana", "Gujana Francuska"},
            {"Hong Kong", "Hongkong"},
            {"Haiti", "Haiti"},
            {"Hungary", "Węgry"},
            {"Indonesia", "Indonezja"},
            {"India", "Indie"},
            {"Ireland", "Irlandia"},
            {"Iceland", "Islandia"},
            {"Israel", "Izrael"},
            {"Italy", "Włochy"},
            {"Japan", "Japonia"},
            {"Jamaica", "Jamajka"},
            {"Jordan", "Jordania"},
            {"Korea", "Korea"},
            {"Lithuania", "Litwa"},
            {"Monaco", "Monako"},
            {"Malaysia", "Malezja"},
            {"Norway", "Norwegia"},
            {"New Zealand", "Nowa Zelandia"},
            {"Poland", "Polska"},
            {"Portugal", "Portugalia"},
            {"Romania", "Rumunia"},
            {"Russia", "Rosja"},
            {"Saudi Arabia", "Arabia Saudyjska"},
            {"United Kingdom", "Zjednoczone Królestwo"},
            {"Spain", "Hiszpania"},
            {"Senegal", "Senegal"},
            {"Serbia", "Serbia"},
            {"Slovakia", "Słowacja"},
            {"Slovenia", "Słowenia"},
            {"Sweden", "Szwecja"},
            {"Thailand", "Tajlandia"},
            {"Tunisia", "Tunezja"},
            {"Turkey", "Turcja"},
            {"Ukraine", "Ukraina"},
            {"United States", "Stany Zjednoczone"}
    };

    @Override
    protected Object[][] getContents() {
        return contents;
    }
}
