package com.example.utp.Wave4.resources;

import java.util.ListResourceBundle;

public class Countries_fr_FR extends ListResourceBundle {
    private final Object[][] contents = {
            {"Aruba", "Aruba"},
            {"Afghanistan", "Afghanistan"},
            {"Angola", "Angola"},
            {"Albania", "Albanie"},
            {"Andorra", "Andorre"},
            {"United Arab Emirates", "Émirats Arabes Unis"},
            {"Argentina", "Argentine"},
            {"Armenia", "Arménie"},
            {"American Samoa", "Samoa américaines"},
            {"Antarctica", "Antarctique"},
            {"French Southern Territories", "Terres australes françaises"},
            {"Antigua and Barbuda", "Antigua-et-Barbuda"},
            {"Australia", "Australie"},
            {"Austria", "Autriche"},
            {"Azerbaijan", "Azerbaïdjan"},
            {"Burundi", "Burundi"},
            {"Belgium", "Belgique"},
            {"Benin", "Bénin"},
            {"Burkina Faso", "Burkina Faso"},
            {"Bangladesh", "Bangladesh"},
            {"Bulgaria", "Bulgarie"},
            {"Bahrain", "Bahreïn"},
            {"Bahamas", "Bahamas"},
            {"Bosnia and Herzegovina", "Bosnie-Herzégovine"},
            {"Belarus", "Biélorussie"},
            {"Bolivia", "Bolivie"},
            {"Brazil", "Brésil"},
            {"Canada", "Canada"},
            {"Ivory Coast", "Côte d'Ivoire"},
            {"Congo", "Congo"},
            {"Colombia", "Colombie"},
            {"Croatia", "Croatie"},
            {"Cuba", "Cuba"},
            {"Cyprus", "Chypre"},
            {"Czechia", "Tchéquie"},
            {"Czech Republic", "République tchèque"},
            {"Switzerland", "Suisse"},
            {"Chie", "Chili"},
            {"China", "Chine"},
            {"Dominica", "Dominique"},
            {"Denmark", "Danemark"},
            {"Egypt", "Égypte"},
            {"Eritrea", "Érythrée"},
            {"Ethiopia", "Éthiopie"},
            {"Finland", "Finlande"},
            {"France", "France"},
            {"Germany", "Allemagne"},
            {"Georgia", "Géorgie"},
            {"Ghana", "Ghana"},
            {"Greece", "Grèce"},
            {"Greenland", "Groenland"},
            {"French Guiana", "Guyane française"},
            {"Hong Kong", "Hong Kong"},
            {"Haiti", "Haïti"},
            {"Hungary", "Hongrie"},
            {"Indonesia", "Indonésie"},
            {"India", "Inde"},
            {"Ireland", "Irlande"},
            {"Iceland", "Islande"},
            {"Israel", "Israël"},
            {"Italy", "Italie"},
            {"Japan", "Japon"},
            {"Jamaica", "Jamaïque"},
            {"Jordan", "Jordanie"},
            {"Korea", "Corée"},
            {"Lithuania", "Lituanie"},
            {"Monaco", "Monaco"},
            {"Malaysia", "Malaisie"},
            {"Norway", "Norvège"},
            {"New Zealand", "Nouvelle-Zélande"},
            {"Poland", "Pologne"},
            {"Portugal", "Portugal"},
            {"Romania", "Roumanie"},
            {"Russia", "Russie"},
            {"Saudi Arabia", "Arabie Saoudite"},
            {"United Kingdom", "Royaume-Uni"},
            {"Spain", "Espagne"},
            {"Senegal", "Sénégal"},
            {"Serbia", "Serbie"},
            {"Slovakia", "Slovaquie"},
            {"Slovenia", "Slovénie"},
            {"Sweden", "Suède"},
            {"Thailand", "Thaïlande"},
            {"Tunisia", "Tunisie"},
            {"Turkey", "Turquie"},
            {"Ukraine", "Ukraine"},
            {"United States", "États-Unis"}
    };

    @Override
    protected Object[][] getContents() {
        return contents;
    }
}
