package com.example.utp.Wave4.resources;

import java.util.ListResourceBundle;

public class Countries_ja_JP extends ListResourceBundle {
    private Object[][] contents = {
            {"Aruba", "アルバ"},
            {"Afghanistan", "アフガニスタン"},
            {"Angola", "アンゴラ"},
            {"Albania", "アルバニア"},
            {"Andorra", "アンドラ"},
            {"United Arab Emirates", "アラブ首長国連邦"},
            {"Argentina", "アルゼンチン"},
            {"Armenia", "アルメニア"},
            {"American Samoa", "アメリカ領サモア"},
            {"Antarctica", "南極"},
            {"French Southern Territories", "フランス領南方・南極地域"},
            {"Antigua and Barbuda", "アンティグア・バーブーダ"},
            {"Australia", "オーストラリア"},
            {"Austria", "オーストリア"},
            {"Azerbaijan", "アゼルバイジャン"},
            {"Burundi", "ブルンジ"},
            {"Belgium", "ベルギー"},
            {"Benin", "ベナン"},
            {"Burkina Faso", "ブルキナファソ"},
            {"Bangladesh", "バングラデシュ"},
            {"Bulgaria", "ブルガリア"},
            {"Bahrain", "バーレーン"},
            {"Bahamas", "バハマ"},
            {"Bosnia and Herzegovina", "ボスニア・ヘルツェゴビナ"},
            {"Belarus", "ベラルーシ"},
            {"Bolivia", "ボリビア"},
            {"Brazil", "ブラジル"},
            {"Canada", "カナダ"},
            {"Ivory Coast", "コートジボワール"},
            {"Congo", "コンゴ"},
            {"Colombia", "コロンビア"},
            {"Croatia", "クロアチア"},
            {"Cuba", "キューバ"},
            {"Cyprus", "キプロス"},
            {"Czechia", "チェコ"},
            {"Czech Republic", "チェコ共和国"},
            {"Switzerland", "スイス"},
            {"Chie", "チリ"},
            {"China", "中国"},
            {"Dominica", "ドミニカ国"},
            {"Denmark", "デンマーク"},
            {"Egypt", "エジプト"},
            {"Eritrea", "エリトリア"},
            {"Ethiopia", "エチオピア"},
            {"Finland", "フィンランド"},
            {"France", "フランス"},
            {"Germany", "ドイツ"},
            {"Georgia", "ジョージア"},
            {"Ghana", "ガーナ"},
            {"Greece", "ギリシャ"},
            {"Greenland", "グリーンランド"},
            {"French Guiana", "フランス領ギアナ"},
            {"Hong Kong", "香港"},
            {"Haiti", "ハイチ"},
            {"Hungary", "ハンガリー"},
            {"Indonesia", "インドネシア"},
            {"India", "インド"},
            {"Ireland", "アイルランド"},
            {"Iceland", "アイスランド"},
            {"Israel", "イスラエル"},
            {"Italy", "イタリア"},
            {"Japan", "日本"},
            {"Jamaica", "ジャマイカ"},
            {"Jordan", "ヨルダン"},
            {"Korea", "韓国"},
            {"Lithuania", "リトアニア"},
            {"Monaco", "モナコ"},
            {"Malaysia", "マレーシア"},
            {"Norway", "ノルウェー"},
            {"New Zealand", "ニュージーランド"},
            {"Poland", "ポーランド"},
            {"Portugal", "ポルトガル"},
            {"Romania", "ルーマニア"},
            {"Russia", "ロシア"},
            {"Saudi Arabia", "サウジアラビア"},
            {"United Kingdom", "イギリス"},
            {"Spain", "スペイン"},
            {"Senegal", "セネガル"},
            {"Serbia", "セルビア"},
            {"Slovakia", "スロバキア"},
            {"Slovenia", "スロベニア"},
            {"Sweden", "スウェーデン"},
            {"Thailand", "タイ"},
            {"Tunisia", "チュニジア"},
            {"Turkey", "トルコ"},
            {"Ukraine", "ウクライナ"},
            {"United States", "アメリカ"}
    };

    @Override
    protected Object[][] getContents() {
        return contents;
    }
}

