package com.example.utp.Wave4.resources;

import java.util.ListResourceBundle;

public class Countries_en_GB extends ListResourceBundle {
    private Object[][] contents = {
            {"Aruba", "Aruba"},
            {"Afghanistan", "Afghanistan"},
            {"Angola", "Angola"},
            {"Albania", "Albania"},
            {"Andorra", "Andorra"},
            {"United Arab Emirates", "United Atab Emirates"},
            {"Argentina", "Argentina"},
            {"Armenia", "Armenia"},
            {"American Samoa", "American Samoa"},
            {"Antarctica", "Antarctica"},
            {"French Southern Territories", "French Southern Territories"},
            {"Antigua and Barbuda", "Antigua and Barbuda"},
            {"Australia", "Australia"},
            {"Austria", "Austria"},
            {"Azerbaijan", "Azerbaijan"},
            {"Burundi", "Burundi"},
            {"Belgium", "Belgium"},
            {"Benin", "Benin"},
            {"Burkina Faso", "Burkina Faso"},
            {"Bangladesh", "Bangladesh"},
            {"Bulgaria", "Bulgaria"},
            {"Bahrain", "Bahrain"},
            {"Bahamas", "Bahamas"},
            {"Bosnia and Herzegovina", "Bosnia and Herzegovina"},
            {"Belarus", "Belarus"},
            {"Bolivia", "Bolivia"},
            {"Brazil", "Brazil"},
            {"Canada", "Canada"},
            {"Ivory Coast", "Ivory Coast"},
            {"Congo", "Congo"},
            {"Colombia", "Colombia"},
            {"Croatia", "Croatia"},
            {"Cuba", "Cuba"},
            {"Cyprus", "Cyprus"},
            {"Czechia", "Czechia"},
            {"Czech Republic", "Czech Republic"},
            {"Switzerland", "Switzerland"},
            {"Chie", "Chile"},
            {"China", "China"},
            {"Dominica", "Dominica"},
            {"Denmark", "Denmark"},
            {"Egypt", "Egypt"},
            {"Eritrea", "Eritrea"},
            {"Ethiopia", "Ethiopia"},
            {"Finland", "Finland"},
            {"France", "France"},
            {"Germany", "Germany"},
            {"Georgia", "Georgia"},
            {"Ghana", "Ghana"},
            {"Greece", "Greece"},
            {"Greenland", "Greenland"},
            {"French Guiana", "French Guiana"},
            {"Hong Kong", "Hong Kong"},
            {"Haiti", "Haiti"},
            {"Hungary", "Hungary"},
            {"Indonesia", "Indonesia"},
            {"India", "India"},
            {"Ireland", "Ireland"},
            {"Iceland", "Iceland"},
            {"Israel", "Israel"},
            {"Italy", "Italy"},
            {"Japan", "Japan"},
            {"Jamaica", "Jamaica"},
            {"Jordan", "Jordan"},
            {"Korea", "Korea"},
            {"Lithuania", "Lithuania"},
            {"Monaco", "Monaco"},
            {"Malaysia", "Malaysia"},
            {"Norway", "Norway"},
            {"New Zealand", "New Zealand"},
            {"Poland", "Poland"},
            {"Portugal", "Portugal"},
            {"Romania", "Romania"},
            {"Russia", "Russia"},
            {"Saudi Arabia", "Saudi Arabia"},
            {"United Kingdom", "United Kingdom"},
            {"Spain", "Spain"},
            {"Senegal", "Senegal"},
            {"Serbia", "Serbia"},
            {"Slovakia", "Slovakia"},
            {"Slovenia", "Slovenia"},
            {"Sweden", "Sweden"},
            {"Thailand", "Thailand"},
            {"Tunisia", "Tunisia"},
            {"Turkey", "Turkey"},
            {"Ukraine", "Ukraine"},
            {"United States", "United States"},
            {"Spain", "Spain"},


    };

    @Override
    protected Object[][] getContents() {
        return contents;
    }

}

